api:
  maps_base_url: "https://maps.apigw.ntruss.com"
  local_base_url: "https://openapi.naver.com"

region:
  include_poi: true
  combine_terms: true
  shorten_suffixes:
    - "특별자치시"
    - "특별시"
    - "광역시"
    - "특별자치도"
    - "자치도"
    - "도"
    - "시"
    - "군"
    - "구"
    - "읍"
    - "면"
    - "리"
    - "동"

search:
  competition_min_count: 20
  radius_start_km: 2
  radius_max_km: 5
  radius_step_km: 1
  use_local_api: true
  local_region_terms: 2

pois:
  enabled: true
  subway_queries:
    - "지하철역"
  landmark_queries:
    - "관광지"
    - "대형마트"
    - "관공서"
  use_local_api: true
  local_display: 10
  allowed_categories:
    subway:
      - "지하철"
      - "전철"
      - "역"
    landmark:
      - "관광"
      - "문화"
      - "공공"
      - "관공서"
      - "공원"
      - "시장"
      - "백화점"
      - "대형마트"
      - "박물관"
      - "미술관"
  allowed_name_keywords:
    subway:
      - "역"
    landmark:
      - "공원"
      - "박물관"
      - "미술관"
      - "문화"
      - "관광"
      - "시장"
      - "백화점"
      - "대형마트"
      - "시청"
      - "구청"
      - "군청"
      - "법원"
      - "경찰서"
      - "소방서"
      - "도서관"
  filter_sets:
    default:
      allowed_categories:
        subway:
          - "지하철"
          - "전철"
          - "역"
        landmark:
          - "관광"
          - "문화"
          - "공공"
          - "관공서"
          - "공원"
          - "시장"
          - "백화점"
          - "대형마트"
          - "박물관"
          - "미술관"
      allowed_name_keywords:
        subway:
          - "역"
        landmark:
          - "공원"
          - "박물관"
          - "미술관"
          - "문화"
          - "관광"
          - "시장"
          - "백화점"
          - "대형마트"
          - "시청"
          - "구청"
          - "군청"
          - "법원"
          - "경찰서"
          - "소방서"
          - "도서관"
    medical:
      allowed_categories:
        subway:
          - "지하철"
          - "전철"
          - "역"
        landmark:
          - "의료"
          - "건강"
          - "병원"
          - "공공"
          - "관공서"
      allowed_name_keywords:
        subway:
          - "역"
        landmark:
          - "병원"
          - "의원"
          - "보건소"
          - "종합병원"
          - "약국"
          - "의과"
          - "치과"
    legal:
      allowed_categories:
        subway:
          - "지하철"
          - "전철"
          - "역"
        landmark:
          - "공공"
          - "관공서"
      allowed_name_keywords:
        subway:
          - "역"
        landmark:
          - "법원"
          - "검찰청"
          - "경찰서"
          - "구청"
          - "시청"
          - "군청"
          - "출입국"
          - "등기소"
    accounting:
      allowed_categories:
        subway:
          - "지하철"
          - "전철"
          - "역"
        landmark:
          - "공공"
          - "관공서"
          - "세무"
      allowed_name_keywords:
        subway:
          - "역"
        landmark:
          - "세무서"
          - "세무"
          - "국세청"
          - "시청"
          - "구청"
          - "군청"

filters:
  address_overlap: true
  exclude_regex: []
  exclude_pairs:
    - industry_terms:
        - "치과"
        - "병원"
        - "의원"
        - "한의원"
        - "피부과"
      modifiers:
        - "밥먹기좋은"
        - "맛있는"
        - "데이트"
        - "회식"
        - "술"
        - "카페"
        - "파티"

keywords:
  joiner: ""
  patterns:
    - ["region", "service"]
    - ["region", "modifier", "service"]
    - ["modifier", "service"]
  modifiers_tiers:
    - ["애기", "아기", "영아", "유아", "영유아", "신생아"]
    - ["어린이", "어린아이", "아동", "아동청소년", "청소년"]
    - ["유치원", "유치원생", "어린이집", "초등학생", "중학생", "고등학생"]
    - ["초등학교", "중학교", "고등학교", "학교", "학생"]
    - ["추천", "인기", "유명한", "전문", "후기좋은", "잘하는", "저렴한", "실력있는"]
  service_terms: []
  service_suffix_rules:
    - suffix: "치료"
      add_suffixes: ["재활", "치료실", "재활실"]
    - suffix: "재활"
      add_suffixes: ["치료", "치료실", "재활실"]
    - suffix: "검사"
      add_suffixes: ["정밀검사", "선별검사"]
    - suffix: "장애"
      add_suffixes: ["장애치료", "장애재활"]
    - suffix: "난청"
      add_suffixes: ["난청치료", "난청재활"]
  service_expansions: []
  name_base_terms:
    - "치과"
    - "성형외과"
    - "피부과"
  name_suffix_terms:
    - "의원"
  name_include_terms:
    - "의원"
  name_expansions:
    - trigger_terms: ["성형외과"]
      include_terms: ["피부과", "피부과의원"]

output:
  keywords_per_group: 1000
  encoding: "cp949"
  template: "naver_csv"
  header_rows:
    - ["키워드를 추가 할 광고그룹ID 와 신규 키워드를 입력하세요.", "", "", "", ""]
    - ["광고그룹ID는 '광고다운로드' 파일에서 확인할 수 있습니다. 입찰가는 쉼표나 '원' 표시를 제외한 숫자만 입력해 주세요.", "", "", "", ""]
    - ["입력은 최대 만(10000)개까지 가능합니다. (광고그룹 당 키워드는 1000개까지 등록가능합니다)", "", "", "", ""]
    - ["그룹의 웹사이트URL이 1개인 경우라도 PC/모바일 URL에 동일하게 2번 입력해주시고 PC/모바일 웹사이트를 별도로 가지고 있는 경우에만 URL을 PC /모바일 구분해서 입력하세요. URL은 http:// 등으로 시작하는 형식이어야 합니다.", "", "", "", ""]
    - ["[중요] 7행부터 입력값이 시스템에 반영됩니다. 1~6행을 삭제하지 마세요. 엑셀에서 저장시 CSV 파일형식을 꼭 확인하시기 바랍니다.", "", "", "", ""]
  columns:
    - "광고그룹ID(필수)"
    - "키워드(필수)"
    - "PC URL(선택)"
    - "모바일 URL(선택)"
    - "키워드입찰가(선택,숫자만)"
  default_pc_url: ""
  default_mobile_url: ""
  default_bid: ""
